export const CATEGORIES = [
    { id: 'mdf-boards', name: 'MDF Boards' },
    { id: 'plywood', name: 'Plywood' },
    { id: 'doors', name: 'Doors' },
    { id: 'flooring', name: 'Flooring' },
    { id: 'timber', name: 'Timber' },
    { id: 'hardware', name: 'Hardware' },
];

export const PRODUCTS = [
    {
        id: 1,
        name: 'MDF Board 18mm',
        category: 'mdf-boards',
        categoryName: 'MDF Boards',
        price: 2500,
        originalPrice: 3000,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=500&fit=crop',
            'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=500&fit=crop',
        ],
        rating: 4.5,
        reviewCount: 42,
        inStock: true,
        stockQty: 150,
        description:
            'Premium 18mm MDF board ideal for furniture, cabinetry, and interior fittings. Smooth surface ready for painting or laminating. Dimensions: 2440mm x 1220mm x 18mm.',
        specs: {
            Thickness: '18mm',
            Size: '2440mm x 1220mm',
            Density: '750 kg/m³',
            Finish: 'Sanded smooth',
            Application: 'Interior use',
        },
        featured: true,
    },
    {
        id: 2,
        name: 'MDF Board 12mm',
        category: 'mdf-boards',
        categoryName: 'MDF Boards',
        price: 1800,
        image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=500&fit=crop'],
        rating: 4.3,
        reviewCount: 28,
        inStock: true,
        stockQty: 200,
        description:
            'Lightweight 12mm MDF board suitable for wall panels, shelving, and light furniture.',
        specs: {
            Thickness: '12mm',
            Size: '2440mm x 1220mm',
            Density: '720 kg/m³',
            Finish: 'Sanded smooth',
            Application: 'Interior use',
        },
        featured: false,
    },
    {
        id: 3,
        name: 'Premium Hardwood Plywood 18mm',
        category: 'plywood',
        categoryName: 'Plywood',
        price: 3500,
        image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=500&fit=crop'],
        rating: 4.8,
        reviewCount: 67,
        inStock: true,
        stockQty: 80,
        description:
            'High-quality hardwood plywood with multiple plies for superior strength. Ideal for flooring, roofing, and structural applications.',
        specs: {
            Thickness: '18mm',
            Size: '2440mm x 1220mm',
            Plies: '13',
            Core: 'Hardwood',
            Glue: 'WBP Marine Grade',
        },
        featured: true,
    },
    {
        id: 4,
        name: 'Marine Grade Plywood 12mm',
        category: 'plywood',
        categoryName: 'Plywood',
        price: 2800,
        image: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=400&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=600&h=500&fit=crop'],
        rating: 4.7,
        reviewCount: 35,
        inStock: true,
        stockQty: 60,
        description: 'Water-resistant marine grade plywood for outdoor and high-moisture environments.',
        specs: {
            Thickness: '12mm',
            Size: '2440mm x 1220mm',
            Grade: 'Marine',
            Glue: 'WBP Type',
            Application: 'Outdoor & Marine',
        },
        featured: false,
    },
    {
        id: 5,
        name: 'Modern Interior Flush Door',
        category: 'doors',
        categoryName: 'Doors',
        price: 8500,
        originalPrice: 10000,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=500&fit=crop'],
        rating: 4.7,
        reviewCount: 53,
        inStock: true,
        stockQty: 45,
        description:
            'Sleek flush interior door with solid core for superior sound insulation. Pre-finished surface ready for painting.',
        specs: {
            Size: '2100mm x 900mm',
            Core: 'Solid Timber',
            Finish: 'Primed',
            Thickness: '40mm',
            Fire: 'FD30 rated',
        },
        featured: true,
    },
    {
        id: 6,
        name: 'Mahogany Solid Wood Door',
        category: 'doors',
        categoryName: 'Doors',
        price: 15000,
        image: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=400&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1567016432779-094069958ea5?w=600&h=500&fit=crop'],
        rating: 4.9,
        reviewCount: 21,
        inStock: true,
        stockQty: 20,
        description:
            'Premium solid mahogany door for exterior or interior use. Naturally resistant to rot and insects.',
        specs: {
            Size: '2100mm x 900mm',
            Material: 'Solid Mahogany',
            Finish: 'Oiled',
            Thickness: '50mm',
            Application: 'Exterior/Interior',
        },
        featured: false,
    },
    {
        id: 7,
        name: 'DecoFloor Laminated Flooring 8mm',
        category: 'flooring',
        categoryName: 'Flooring',
        price: 1200,
        image: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=400&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=600&h=500&fit=crop'],
        rating: 4.6,
        reviewCount: 89,
        inStock: true,
        stockQty: 500,
        description:
            'Durable laminated flooring with realistic wood texture. Easy click-lock installation. Price per square metre.',
        specs: {
            Thickness: '8mm',
            Coverage: '1 m²/plank',
            AC: 'AC4 (Heavy Domestic)',
            Finish: 'Matt',
            Installation: 'Click-lock floating',
        },
        featured: true,
    },
    {
        id: 8,
        name: 'Vinyl Plank Flooring 5mm',
        category: 'flooring',
        categoryName: 'Flooring',
        price: 950,
        originalPrice: 1100,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=500&fit=crop'],
        rating: 4.4,
        reviewCount: 44,
        inStock: true,
        stockQty: 300,
        description:
            '100% waterproof vinyl plank flooring ideal for kitchens and bathrooms. Price per square metre.',
        specs: {
            Thickness: '5mm',
            Material: '100% Vinyl',
            Waterproof: 'Yes',
            Finish: 'Embossed',
            Installation: 'Click-lock',
        },
        featured: false,
    },
    {
        id: 9,
        name: 'Cypress Timber Post 100x100mm',
        category: 'timber',
        categoryName: 'Timber',
        price: 850,
        image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=500&fit=crop'],
        rating: 4.5,
        reviewCount: 18,
        inStock: true,
        stockQty: 120,
        description:
            'Treated cypress timber post for structural and fencing applications. Length: 3 metres.',
        specs: {
            Size: '100mm x 100mm x 3000mm',
            Species: 'Cypress',
            Treatment: 'CCA treated',
            Application: 'Structural/Fencing',
        },
        featured: false,
    },
    {
        id: 10,
        name: 'Concealed Hinge Set (10 pairs)',
        category: 'hardware',
        categoryName: 'Hardware',
        price: 450,
        image: 'https://images.unsplash.com/photo-1609659905049-55f9ed73d3f6?w=400&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1609659905049-55f9ed73d3f6?w=600&h=500&fit=crop'],
        rating: 4.6,
        reviewCount: 112,
        inStock: true,
        stockQty: 1000,
        description:
            'European-style concealed cabinet hinges with soft-close mechanism. Pack of 10 pairs with mounting plates.',
        specs: {
            Type: 'Full overlay concealed',
            Opening: '110°',
            'Soft close': 'Yes',
            Material: 'Steel with nickel finish',
            Pack: '10 pairs',
        },
        featured: false,
    },
    {
        id: 11,
        name: 'Cabinet Drawer Slides 450mm (5 pairs)',
        category: 'hardware',
        categoryName: 'Hardware',
        price: 680,
        image: 'https://images.unsplash.com/photo-1609659905049-55f9ed73d3f6?w=400&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1609659905049-55f9ed73d3f6?w=600&h=500&fit=crop'],
        rating: 4.7,
        reviewCount: 76,
        inStock: false,
        stockQty: 0,
        description:
            'Heavy-duty undermount drawer slides with smooth full-extension and soft-close feature. Pack of 5 pairs.',
        specs: {
            Length: '450mm',
            Type: 'Undermount',
            Load: '40kg per pair',
            Feature: 'Soft close & full extension',
            Pack: '5 pairs',
        },
        featured: false,
    },
    {
        id: 12,
        name: 'MDF Moisture Resistant 18mm',
        category: 'mdf-boards',
        categoryName: 'MDF Boards',
        price: 3200,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=500&fit=crop'],
        rating: 4.6,
        reviewCount: 31,
        inStock: true,
        stockQty: 90,
        description:
            'Moisture-resistant MDF (green core) for use in humid environments like kitchens and bathrooms.',
        specs: {
            Thickness: '18mm',
            Size: '2440mm x 1220mm',
            Type: 'Moisture Resistant',
            Core: 'Green (MR)',
            Application: 'Kitchens & Bathrooms',
        },
        featured: false,
    },
];

export const getFeaturedProducts = () => PRODUCTS.filter((p) => p.featured);

export const getProductById = (id) => PRODUCTS.find((p) => p.id === Number(id));

export const getProductsByCategory = (categoryId) =>
    PRODUCTS.filter((p) => p.category === categoryId);

export const searchProducts = (query) => {
    const q = query.toLowerCase();
    return PRODUCTS.filter(
        (p) =>
            p.name.toLowerCase().includes(q) ||
            p.categoryName.toLowerCase().includes(q) ||
            p.description.toLowerCase().includes(q)
    );
};
